### PR TITLE
watsonLlama project merge

### PR DESCRIPTION
**Pull request by gabrieltsants**
**I recommend testing before accepting the pull request by running the `configure_llama.linux.sh` script and validating that everything is working correctly** :)

### Some things I added (that I remember):

* Argparse for parameters, with default -h for help.
* **-w** for a summary of a Wiki article.
* Error messages in case of bot response failure or lack of connection when accessing the Wiki.
* Optional **-n** parameter for custom tokens.
* _.env_example_ with pre-defined values, now the command parameters/questions can be different for each one, as well as the models.
* Script for initial installation that clones llama.cpp, configure the _.env_ and downloads the default model 7B. It can be changed in the .env as mentioned.
* Functions for the CLI such as custom colors and a parameter for ASCII art that may be added in the future
* Default N for the command (I did this in my project because the model recommended `rm -rf /` when I asked to list files in the current directory, I thought it was dangerous to leave Y as the default haha) But if you want to return to Y, no problem.

###  Things I changed before merging the project:

* Removed all artwork/ASCII art/name and changed it to Llamaterm/llama-terminal-completion.
* Changed the argparse description example to the standard added in the LlamaTerm project _README_.
* Changed the command response message to the LlamaTerm default.

### Improvements that I was planning to add to my project in the future and might be useful:

* History/log generator as we talked about, there is already a file called **logManager.py** for this future implementation, perhaps it can be activated/deactivated in the .env.
* A script with multiple choice of models, or leaving a specific model for code like WizardCoder, as I realized that the default model is quite flawed with some simple commands.

### CODE REVIEW

**Comment by adammpkins** [comment]
This looks good, and works great. Did you want to update the docs along with this PR, or should I @gabrieltsants ?

**Comment by gabrieltsants** [comment]
Great to hear you liked it! Just updated the doc. Feel free to reach out if you need anything. @adammpkins

**Comment by gabrieltsants** [comment]
The ASCII art looks great!

Just a heads up: I noticed that the .env_example file was [deleted](https://github.com/adammpkins/llama-terminal-completion/commit/2e165b69e021e4fe01aa80f3f4c7c707ec2a6ac9). As a result, the README installation section may not work correctly without this file since it already contains some pre-defined values to simplify the process for the end user when creating the .env file. The installation script also relies on this file to set default variables.

I've been working extensively with Laravel recently, and setting a default example file was the first solution that came to mind. However, there may be better approaches 🤔

**Comment by adammpkins** [comment]
@gabrieltsants You're totally right.  It was a mistake on my part. I modified the file and renamed it rather than copying it.

**Comment by gabrieltsants** [comment]
@adammpkins 

> Btw, I'm also primarily a PHP/Laravel developer.

Cool!

> You're totally right. It was a mistake on my part. I modified the file and renamed it rather than copying it. Should be fixed. 

No problem, it happens haha

**Pull request merged**
